name = "valet-parking-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "valet-db"
database_id = "0c3d5545-adc7-47ac-84b6-02405dd1df22"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "valet-parking-photos"

[vars]
JWT_SECRET = "p8X3mA9qL7sT2vB4yZ6rN1kF0wH9cQ5d"

