INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Gonzalez V., Billy', 'C001', 'director', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Ramos B., José Gregorio', 'C002', 'director', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Quintero F., Richard A.', 'C003', 'director', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Tinoco F., Gladys S.', 'S001', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Ortiz S., Gustavo A.', 'S002', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Pimental V., José de los S.', 'P001', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Puertas S., Nicolas E.', 'P002', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Almarza, Maria J.', 'P003', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('León F., Javier E.', 'B011', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Caraballo V., Jefferson R.', 'B012', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Ramos B., Jesús D.', 'B013', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Gil S., Mario R.', 'B014', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Flores D., Carla S.', 'B015', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Gonzalez D., Jorman R.', 'B016', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Mendoza, Moises', 'L075', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Lopez R., Alvaro J.', 'B026', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Seijas A., Yerley K.', 'B027', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Rodriguez G., Ricardo E.', 'B028', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Malcom B., José Miguel', 'B030', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Franco G., Franklin J.', 'B031', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Franco F., Freymar de Jesú', 'B032', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Musso P., Leonardo F.', 'B033', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Ortega G., Miguel M.', 'B041', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Falcon C., Daniela del C.', 'B042', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Arias C., Elianis S.', 'B043', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Tinoco F., Johan J.', 'B044', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Chapano T., Anthony A.', 'B045', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Martinez H., Douglas R.', 'B046', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Burgos, Wilmer F.', 'B047', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Contreras B., Steven C.', 'B048', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Guevara B., Luis Jose', 'L001', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Echenique P., Wisorman', 'L002', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Rivas M., Elvis D.', 'L003', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Muñoz, Alberth J.', 'L004', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Salazar S., Luis Manuel', 'L005', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Huezo G., Maifer A.', 'L006', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Marcano S., Jhonny E.', 'L007', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Rada A., Rony M.', 'L008', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Abella F., Jose R.', 'L009', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Rodriguez O., Neudal D.', 'L010', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Lombano Q., Nelson E.', 'L011', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Vivas C., Yerlusa R.', 'L012', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Hernandez R., Victor J.', 'L013', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Muñoz, Maria Cristely', 'L014', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Perdomo V., Yaniela del C', 'L015', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Hung G., Samuel A.', 'L016', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Clemente G., Jesús Alejan', 'L017', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Meza, Maria I.', 'L018', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Briceño B., Hector J.', 'L019', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Gonzalez G., Ana D.', 'L020', 'driver', CURRENT_TIMESTAMP);
