INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Pimentel P. Jonathan A.', 'L021', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Noguera R., Luis L.', 'L022', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Herrera M., Franklin J.', 'L023', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Tovar C. Renán E.', 'L024', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Caballero L. Nikol A.', 'L025', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Soto M., Edgardo J.', 'L027', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Gonzalez F. Giusi I.', 'L028', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Rodriguez R., Wildrem D.', 'L029', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Seijas P., Algeni J.', 'L030', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Garcia M., Yudvel C.', 'L031', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Vielma R., Edvin A.', 'L032', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Marcano R., Lainny J.', 'L033', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Vizcaíno M., Angela S.', 'L034', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Puertas L., Lausmar D.', 'L035', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Gonzalez D., Jesus David', 'L036', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Viera M., Antonio J.', 'L037', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Lopez J., Angel S.', 'L038', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Urbina D., Anthony J.', 'L039', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Marcano P., Jhonny E.', 'L040', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Guerrero V. Javier J.', 'L041', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Hernandez G., Jesus S.', 'L042', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Salazar, Gerardo', 'L043', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Lyon S., Jose V.', 'L044', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Suarez C., Yusbeli M.', 'L045', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Gonzalez M., Leonel A.', 'L046', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Avila S., Adrian A.', 'L047', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Ramos M., David A.', 'L048', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Martinez A., Jose F.', 'L049', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Salazar T., Daniel A.', 'L050', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Bastardo M. Eduardo A.', 'L051', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Rodriguez B., Fabio A.', 'L052', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Alvarez C. Deivis G.', 'L053', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Rodriguez R. Jonathan D.', 'L054', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Toussaint, Jorge', 'L055', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Rodriguez B., Henry A.', 'L056', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Henriquez, Luis F.', 'L057', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Vitta L. Jomaner L.', 'L058', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Hernandez R., Jorman J.', 'L059', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Armas A., Maikol A.', 'L060', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Narváez C., Wilmer R.', 'L061', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Armas S., Bryan M.', 'L062', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Gonzalez, Roaxel', 'L063', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Hernandez C., Ricardo E.', 'L064', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Romero, Angel A.', 'L065', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Romo, Luis', 'L066', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Uzcategui P., Diego F.', 'L067', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Vasquez T., Victor J.', 'L068', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Barrios M., Alejandro J.', 'L069', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Contreras L., Hector D.', 'L070', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Guerrero G., Gabriel A.', 'L071', 'driver', CURRENT_TIMESTAMP);
