INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Gonzalez V., Billy', 'C001', 'director', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Ramos B., José Gregorio', 'C002', 'director', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Quintero F., Richard A.', 'C003', 'director', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Tinoco F., Gladys S.', 'S001', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Ortiz S., Gustavo A.', 'S002', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Pimental V., José de los S.', 'P001', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Puertas S., Nicolas E.', 'P002', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Almarza, Maria J.', 'P003', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('León F., Javier E.', 'B011', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Caraballo V., Jefferson R.', 'B012', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Ramos B., Jesús D.', 'B013', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Gil S., Mario R.', 'B014', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Flores D., Carla S.', 'B015', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Gonzalez D., Jorman R.', 'B016', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Mendoza, Moises', 'L075', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Lopez R., Alvaro J.', 'B026', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Seijas A., Yerley K.', 'B027', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Rodriguez G., Ricardo E.', 'B028', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Malcom B., José Miguel', 'B030', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Franco G., Franklin J.', 'B031', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Franco F., Freymar de Jesú', 'B032', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Musso P., Leonardo F.', 'B033', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Ortega G., Miguel M.', 'B041', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Falcon C., Daniela del C.', 'B042', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Arias C., Elianis S.', 'B043', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Tinoco F., Johan J.', 'B044', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Chapano T., Anthony A.', 'B045', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Martinez H., Douglas R.', 'B046', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Burgos, Wilmer F.', 'B047', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Contreras B., Steven C.', 'B048', 'supervisor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Guevara B., Luis Jose', 'L001', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Echenique P., Wisorman', 'L002', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Rivas M., Elvis D.', 'L003', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Muñoz, Alberth J.', 'L004', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Salazar S., Luis Manuel', 'L005', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Huezo G., Maifer A.', 'L006', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Marcano S., Jhonny E.', 'L007', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Rada A., Rony M.', 'L008', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Abella F., Jose R.', 'L009', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Rodriguez O., Neudal D.', 'L010', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Lombano Q., Nelson E.', 'L011', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Vivas C., Yerlusa R.', 'L012', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Hernandez R., Victor J.', 'L013', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Muñoz, Maria Cristely', 'L014', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Perdomo V., Yaniela del C', 'L015', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Hung G., Samuel A.', 'L016', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Clemente G., Jesús Alejan', 'L017', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Meza, Maria I.', 'L018', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Briceño B., Hector J.', 'L019', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Gonzalez G., Ana D.', 'L020', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Pimentel P. Jonathan A.', 'L021', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Noguera R., Luis L.', 'L022', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Herrera M., Franklin J.', 'L023', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Tovar C. Renán E.', 'L024', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Caballero L. Nikol A.', 'L025', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Soto M., Edgardo J.', 'L027', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Gonzalez F. Giusi I.', 'L028', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Rodriguez R., Wildrem D.', 'L029', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Seijas P., Algeni J.', 'L030', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Garcia M., Yudvel C.', 'L031', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Vielma R., Edvin A.', 'L032', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Marcano R., Lainny J.', 'L033', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Vizcaíno M., Angela S.', 'L034', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Puertas L., Lausmar D.', 'L035', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Gonzalez D., Jesus David', 'L036', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Viera M., Antonio J.', 'L037', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Lopez J., Angel S.', 'L038', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Urbina D., Anthony J.', 'L039', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Marcano P., Jhonny E.', 'L040', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Guerrero V. Javier J.', 'L041', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Hernandez G., Jesus S.', 'L042', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Salazar, Gerardo', 'L043', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Lyon S., Jose V.', 'L044', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Suarez C., Yusbeli M.', 'L045', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Gonzalez M., Leonel A.', 'L046', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Avila S., Adrian A.', 'L047', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Ramos M., David A.', 'L048', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Martinez A., Jose F.', 'L049', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Salazar T., Daniel A.', 'L050', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Bastardo M. Eduardo A.', 'L051', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Rodriguez B., Fabio A.', 'L052', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Alvarez C. Deivis G.', 'L053', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Rodriguez R. Jonathan D.', 'L054', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Toussaint, Jorge', 'L055', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Rodriguez B., Henry A.', 'L056', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Henriquez, Luis F.', 'L057', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Vitta L. Jomaner L.', 'L058', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Hernandez R., Jorman J.', 'L059', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Armas A., Maikol A.', 'L060', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Narváez C., Wilmer R.', 'L061', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Armas S., Bryan M.', 'L062', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Gonzalez, Roaxel', 'L063', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Hernandez C., Ricardo E.', 'L064', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Romero, Angel A.', 'L065', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Romo, Luis', 'L066', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Uzcategui P., Diego F.', 'L067', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Vasquez T., Victor J.', 'L068', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Barrios M., Alejandro J.', 'L069', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Contreras L., Hector D.', 'L070', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Guerrero G., Gabriel A.', 'L071', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Riera G., José B.', 'L072', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Jira H., Frederick A.', 'L073', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Panaguica, Joan', 'L074', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Perez C. William J.', 'L075', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Chacon, Gloris', 'L076', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Rojas G., Christian A.', 'L077', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Gaceitte G., Iván', 'L078', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Velasco G., Cesar A.', 'L079', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Molina B., Pedro A.', 'L080', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Graziani A., Jhan A.', 'L081', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Herrera, Maikel A.', 'L083', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Sequera C., Marco A.', 'L084', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Muñoz, Adalgisa', 'L085', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Rivas, Victor', 'L086', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Perez P., Arturo J.', 'L087', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Velasquez, Anthony', 'L088', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Guacarán G., Franklin J.', 'L089', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Alfonso M., Franklin J.', 'L090', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Forrero G., German D.', 'L091', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Farfan T., Anthony J.', 'L092', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Perez Q., Eduardo L.', 'L093', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Guzman Z., Jorman J.', 'L094', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Rodriguez, Kristian', 'L096', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Toussaint F., Felix J.', 'L097', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Diaz S., Yandry J.', 'L098', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Quintero L., Hover A.', 'L099', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Cordero V., Yelfre P.', 'L100', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Valera A., Frank J.', 'L101', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Romel, Samuel', 'L102', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Gil E., Eduardo Y.', 'L104', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Landa L., Arnaldo', 'L105', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Nuñez, Yonathan G.', 'L108', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Sanchez G., Kleidismar A.', 'L109', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Soto P., Keiver F.', 'L110', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Coronado M., David J.', 'L111', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Vivas O., Yerlusa (Yulya)', 'L113', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Vivas C., Abraham A.', 'L114', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Garcia, Edgar E.', 'L115', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Suarez, Ruben', 'L116', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Hernandez, Sandy', 'L117', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Bastardo, Eduardo', 'L118', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Garcia, Tadey', 'L119', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Suarez, Glady', 'L120', 'driver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO users (name, pin_hash, role, created_at) VALUES ('Gutierrez, Albeny', 'L121', 'driver', CURRENT_TIMESTAMP);
